# Generated by Django 2.2 on 2021-01-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(blank=True, max_length=50, null=True)),
                ('desination', models.CharField(blank=True, max_length=50, null=True)),
                ('desginkdda', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expid', models.CharField(blank=True, max_length=10, null=True)),
                ('expname', models.CharField(blank=True, max_length=50, null=True)),
                ('expmode', models.CharField(choices=[('CASH', 'cash'), ('CHEQUE', 'cheque'), ('DEMAND DRAFT', 'demand draft')], max_length=15)),
                ('amount', models.IntegerField(default=0)),
                ('expreason', models.CharField(max_length=50)),
                ('expby', models.CharField(blank=True, max_length=50, null=True)),
                ('expdate', models.DateField()),
                ('detail', models.TextField()),
                ('bankname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('chequeordd', models.IntegerField(blank=True, default=0, null=True)),
                ('dateinbank', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etypeid', models.IntegerField()),
                ('etypename', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incid', models.CharField(blank=True, max_length=10, null=True)),
                ('incname', models.CharField(blank=True, max_length=50, null=True)),
                ('incdate', models.DateField()),
                ('incmode', models.CharField(choices=[('CASH', 'cash'), ('CHEQUE', 'cheque'), ('DEMAND DRAFT', 'demand draft')], max_length=15)),
                ('incamt', models.IntegerField(default=0)),
                ('increason', models.CharField(max_length=50)),
                ('incby', models.CharField(max_length=50)),
                ('bankname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('chequeordd', models.IntegerField(blank=True, default=None, null=True)),
                ('dateinbank', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField()),
                ('typename', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashinhand', models.IntegerField(blank=True, null=True)),
                ('cashatbank', models.IntegerField(blank=True, null=True)),
                ('cashatbankexp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
